### ISSUE TITLE
Cache loading error

### ISSUE THREAD

**Issue by Michielo1** [Michielo1/BigBrotherRepo#15]
**Describe the bug**
Getting a cache loading error `java.lang.NoSuchMethodError` upon starting server.

**To Reproduce**
1. Start server
2. Close server
3. Malform bigbrother/playerdata/cache.json (or it has malformed on its own)
4. start up server & get error

**Additional context**
```
Error occurred while enabling BigBrother v1.2.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(com.google.gson.stream.JsonReader)'
        at com.michielo.utils.data.cache.CacheUtil.loadCache(CacheUtil.java:52) ~[?:?]
        at com.michielo.BigBrother.cacheWorker(BigBrother.java:131) ~[?:?]
        at com.michielo.BigBrother.onEnable(BigBrother.java:56) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-792]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-792]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Michielo1** [comment]
fixed in 1.3.0
